version: '3.7'

services:
  binance-redis:
    image: redis:6.0
    networks:
      - ingress
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 120M
      restart_policy:
        condition: on-failure
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf

  binance-mongo:
    image: mongo:3.2.20-jessie
    command:
      - "mongod"
      - "--wiredTigerCacheSizeGB"
      - "1"
    networks:
      - ingress
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 1200M
      restart_policy:
        condition: on-failure
    ports:
      - 27017:27017

  binance-mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    networks:
      - ingress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: binance-mongo
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure

  binance-redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    networks:
      - ingress
    ports:
      - 8082:8081
    environment:
      REDIS_HOST: 'binance-redis'
      REDIS_PORT: 6379
      REDIS_PASSWORD:
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure

  tradingview:
    image: sardorabdullaev/binance-trailing-trade-bot:tradingview
    networks:
      - ingress
    restart: unless-stopped
    ports:
      - 8083:8080
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    deploy:
      replicas: 1

  binance-bot:
    image: sardorabdullaev/binance-trailing-trade-bot:0.0.85
    networks:
      - ingress
    environment:
      BINANCE_LIVE_API_KEY: ''
      BINANCE_LIVE_SECRET_KEY: ''
      BINANCE_TEST_API_KEY: ''
      BINANCE_TEST_SECRET_KEY: ''
      BINANCE_MODE: 'live'
      BINANCE_TZ: 'Europe/Berlin'
      BINANCE_SLACK_ENABLED: 'false'
      BINANCE_JOBS_ALIVE_ENABLED: 'true'
      BINANCE_JOBS_TRAILING_TRADE_ENABLED: 'true'
      BINANCE_MONGO_HOST: 'binance-mongo'
      BINANCE_MONGO_PORT: 27017
      BINANCE_MONGO_DATABASE: 'binance-bot'
      BINANCE_LOCAL_TUNNEL_ENABLED: 'true'
      BINANCE_REDIS_HOST: 'binance-redis'
      BINANCE_REDIS_PORT: 6379
      BINANCE_REDIS_PASSWORD:
      BINANCE_REDIS_DB: 0
    ports:
      - 8080:80
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      restart_policy:
        condition: on-failure

networks:
  ingress:
    driver: overlay
    attachable: true

volumes:
  redis_data:
  mongo_data:
