version: '3.7'

services:
  crypto-trading:
    image: sardorabdullaev/binance-trend-trade-bot
    networks:
      - ingress
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./supported_coin_list:/app/supported_coin_list
      - ./data:/app/data
      - logs_vol:/app/logs
      - ./config/apprise.yml:/app/config/apprise.yml
    command: python -m binance_trade_bot
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: 136M
      restart_policy:
        condition: on-failure
    environment:
      - PYTHONUNBUFFERED=1

#  api:
#    image: sardorabdullaev/binance-trend-trade-bot
#    networks:
#      - ingress
#    working_dir: /app
#    volumes:
#      - ./user.cfg:/app/user.cfg
#      - data_vol:/app/data
#      - logs_vol:/app/logs
#    command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
#    deploy:
#      mode: replicated
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.2"
#          memory: 105M
#      restart_policy:
#        condition: on-failure
#    depends_on:
#      - crypto-trading

#  sqlitebrowser:
#    image: ghcr.io/linuxserver/sqlitebrowser
#    networks:
#      - ingress
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/Berlin
#    volumes:
#      - data_config_vol:/config
#      - data_vol:/data
#    deploy:
#      mode: global
#    ports:
#      - 3000:3000

networks:
  ingress:
    driver: overlay
    attachable: true

volumes:
  logs_vol:
