version: '3.7'

services:
  crypto-trading:
    image: sardorabdullaev/binance-trend-trade-bot
    networks:
      - ingress
    container_name: binance_trader
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - ./supported_coin_list:/app/supported_coin_list
      - data_vol:/app/data
      - logs_vol:/app/logs
      - ./config/apprise.yml:/app/config/apprise.yml
    command: python -m binance_trade_bot
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
    environment:
      - PYTHONUNBUFFERED=1

  api:
    image: sardorabdullaev/binance-trend-trade-bot
    networks:
      - ingress
    container_name: binance_trader_api
    working_dir: /app
    volumes:
      - ./user.cfg:/app/user.cfg
      - data_vol:/app/data
      - logs_vol:/app/logs
    ports:
      - 5123:5123
    command: gunicorn binance_trade_bot.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5123
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
    depends_on:
      - crypto-trading

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser
    container_name: sqlitebrowser
    networks:
      - ingress
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - data_config_vol:/config
      - data_vol:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == worker ]
    ports:
      - 3000:3000

networks:
  ingress:
    driver: overlay
    attachable: true

volumes:
  data_vol:
  data_config_vol:
  logs_vol:
